### ISSUE TITLE
Implement labels/catalog support for recipes

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/recipe-manager#3]
- Modify the MongoDB structure to incorporate labels for each recipe, allowing more than one label for a recipe. (e.g., Indian, Favorite)
- Update the recipe creation form to allow users to add labels.

**Comment by namrataaravinda** [comment]
can i get this assigned?

**Comment by Samyukta-b** [comment]
!assign @namrataaravinda 60

**Comment by Delta18-Git** [comment]
@Samyukta-b would this be the right approach?: https://github.com/Delta18-Git/recipe-manager/commit/21c9da93f11c1032e3751bc98e15d2d39f65ed71 https://github.com/Delta18-Git/recipe-manager/commit/036eb544a9869d6523a3ab81fcf520e207b789a5

I wanted to know as I don't have IDEA installed so it is a bit hard to actually test for me.

**Comment by Delta18-Git** [comment]
See #9 @Samyukta-b
