### ISSUE TITLE
Custom labels/catalog support

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/recipe-manager#4]
If both #1 and #3 are implemented, update the recipe display page so that users can edit the labels or create new labels.

**Comment by sampada115** [comment]
can you assign this?

**Comment by sampada115** [comment]
@Samyukta-b

**Comment by Samyukta-b** [comment]
@sampada115 this issue cannot be completed without finishing #1 and #3. once they are over, this issue can be worked with

**Comment by sampada115** [comment]
ok
