### ISSUE TITLE
Search functionality support for labels/catalog

### ISSUE THREAD

**Issue by Samyukta-b** [acmpesuecc/recipe-manager#5]
If both #2 and #3 are implemented, enable users to search for recipes based on labels on the search page.

**Comment by Harshinigrandhi2005** [comment]
can u assign this @Samyukta-b

**Comment by Samyukta-b** [comment]
@Harshinigrandhi2005 issue #2 and #3 need to be completed before this issue, would you like to do any of those instead? please comment under those

**Comment by Aditya-C-S** [comment]
so can i do this , or i need someone to finish #2 and #3 for me to do this

**Comment by Samyukta-b** [comment]
@Aditya-C-S hi, yes #2 and #3 need to be implemented, currently nobody is working on #3, woudl you liek to work on that? please comment on that issue if so

**Comment by Aditya-C-S** [comment]
i want to do #2 but its already assigned to someone else

**Comment by sampada115** [comment]
can you assign this?

**Comment by Samyukta-b** [comment]
!deassign

**Comment by Samyukta-b** [comment]
!assign @sampada115 60

**Comment by Samyukta-b** [comment]
!deassign

**Comment by sampada115** [comment]
can you assign again?

**Comment by sampada115** [comment]
or is there any issue?

**Comment by Samyukta-b** [comment]
@sampada115 yes you can do #2, i'm sorry but to do #5 you'll need to do #2 and #3.

**Comment by Samyukta-b** [comment]
@sampada115 go comment underneath #2
